version: "3"

services:
  node:
    image: node:16
    container_name: store_manager_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_HOST: ${MYSQLHOST}
  db:
    container_name: store_manager_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
      MYSQL_PORT: ${MYSQLPORT}
    ports:
      - 3306:3306